# -- Main Menu --

[[main]]
  name = "Work"
  pageRef = "work"
  weight = 10

[[main]]
  name = "Writing"
  pageRef = "writing"
  weight = 20

[[main]]
  name = "Labs"
  pageRef = "labs"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

[[main]]
  identifier = "appearance"
  weight = 90
  [main.params]
    action = "appearance"

[[footer]]
  name = "CV"
  pageRef = "cv"
  weight = 10
