# -- Main Menu --

[[main]]
  name = "Work"
  pageRef = "work"
  weight = 10

[[main]]
  name = "Thoughts"
  pageRef = "thoughts"
  weight = 20

[[main]]
  name = "Artifacts"
  pageRef = "artifacts"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

[[main]]
  identifier = "appearance"
  weight = 90
  [main.params]
    action = "appearance"
